name: UI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Zip output
      uses: papeloto/action-zip@v1
      with:
        files: build/
        dest: investager-ui.zip
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: investager-ui
        path: investager-ui.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          name: investager-ui
      - name: Copy artifact
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          source: "investager-ui.zip"
          target: "/home/investager"
      - name: Upgrade
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /home/investager
            zip -r "$(date +%Y%m%d_%H%M%S)_ui.zip" ui/
            rm -rf ui
            unzip investager-ui.zip -d ui
            rm investager-ui.zip
